package com.mpsp.cc_auth_service.constants;

public enum UserRole {
  ADMIN,
  PRINCIPAL,
  TEACHER,
  STUDENT,
  POC,
  HELPDESKUSER,
  HELPDESKADMIN,
  TECHSUPPORTUSER,
  TECHSUPPORTADMIN,
  OPERATIONSUSER,
  OPERATIONSADMIN
}
